### PR TITLE
Libreoffice 5

### PR DESCRIPTION
**Pull request by nathansamson**
Updates to LO 5.0.2 Also includes mesa / GLU which seems to be necessary for newer LO versions.

### CODE REVIEW

**Comment by wintondeshong** [comment]
+1 for merging pull request. Current 4.x version does not work on heroku.

**Comment by nathansamson** [comment]
Note that with this pull request you are certainly going to run into #6

**Comment by wintondeshong** [comment]
Thanks for the note @nathansamson

**Comment by nathansamson** [comment]
If you go to
https://github.com/nathansamson/heroku-buildpack-libreoffice/network you can actually see there are people that have improved on my work.

Mainly https://github.com/VBykovec/heroku-buildpack-libreoffice/commit/32b729eb30d709473d1b2f38d08f2548f3c26a1e which seems to have improved disk usage by removing unneeded files.

Note that I did not test that version, and I am not sure if it resolves the problem completely, but you might want to try that version.

**Comment by rishihahs** [comment]
I'll merge this, regardless of #6; thanks for the work @nathansamson.

**Comment by wintondeshong** [comment]
Yes, thank you for all the work. -- For the record, Heroku bumped me to 500MB slug size in a matter of 10 minutes of the support request.

**Pull request merged**
